
<?php

if($var==1)
{

echo "
<nav class=\"navmenu\">
		<a href=\"index.php\" class=\"current\">Home</a>
		<a href=\"jobs.php\">Jobs</a>
		<a href=\"apply.php\">Apply</a>
		<a href=\"about.php\">About Us</a>
		<a href=\"mailto:102019464@student.swin.edu.au\">Contact Developer</a>
 </nav>";
		}
if($var==2)
{

	echo "
	     <nav class=\"navmenu\">
	         <a href=\"index.php\" >Home</a>
	         <a href=\"jobs.php\" class=\"current\">Jobs</a>
	         <a href=\"apply.php\">Apply</a>
	         <a href=\"about.php\">About Us</a>
	         <a href=\"mailto:102019464@student.swin.edu.au\">Contact Developer</a>
	      </nav>";

}

if($var==3)
{

	echo "
	     <nav class=\"navmenu\">
	         <a href=\"index.php\" >Home</a>
	         <a href=\"jobs.php\" >Jobs</a>
	         <a href=\"apply.php\" >Apply</a>
	         <a href=\"about.php\" class=\"current\">About Us</a>
	         <a href=\"mailto:102019464@student.swin.edu.au\">Contact Developer</a>
	      </nav>";

}
if($var==4)
{

	echo "
	     <nav class=\"navmenu\">
	         <a href=\"index.php\" >Home</a>
	         <a href=\"jobs.php\" >Jobs</a>
	         <a href=\"apply.php\" class=\"current\">Apply</a>
	         <a href=\"about.php\" >About Us</a>
	         <a href=\"mailto:102019464@student.swin.edu.au\">Contact Developer</a>
	      </nav>";

}

?>
